// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using therapist_api;

namespace therapist_api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191126195813_InitialCreateWithTableSet")]
    partial class InitialCreateWithTableSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("therapist_api.Models.therapist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bach");

                    b.Property<string>("Certified");

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<int>("HomePhone");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("N1");

                    b.Property<DateTime>("N2");

                    b.Property<DateTime>("N3");

                    b.Property<DateTime>("N4");

                    b.Property<DateTime>("P101");

                    b.Property<DateTime>("P202");

                    b.Property<string>("PostalCode");

                    b.Property<DateTime>("S1");

                    b.Property<DateTime>("S2");

                    b.Property<DateTime>("S3");

                    b.Property<DateTime>("S4");

                    b.Property<string>("SeminarsTaken");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<int>("Website");

                    b.Property<int>("WorkPhone");

                    b.HasKey("Id");

                    b.ToTable("Therapists");
                });
#pragma warning restore 612, 618
        }
    }
}
